version: '3.8'
services:
  db:
    image: postgres:15
    container_name: easy_inventory_db
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: easy_inventory_app
    env_file:
      - .env.prod
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: >
      sh -c "
      npx prisma migrate deploy &&
      npx prisma db seed &&
      npx prisma generate &&
      npm start
      "

volumes:
  postgres_data:
