import { CHART_FOR, MonthlyChartItem, MONTHS } from "@/definitions";

export const monthlyChartData: MonthlyChartItem[] = [
	{ month: MONTHS.ENERO, [CHART_FOR.PAID]: 186, [CHART_FOR.CANCELED]: 80 },
	{ month: MONTHS.FEBRERO, [CHART_FOR.PAID]: 305, [CHART_FOR.CANCELED]: 200 },
	{ month: MONTHS.MARZO, [CHART_FOR.PAID]: 237, [CHART_FOR.CANCELED]: 120 },
	{ month: MONTHS.ABRIL, [CHART_FOR.PAID]: 73, [CHART_FOR.CANCELED]: 190 },
	{ month: MONTHS.MAYO, [CHART_FOR.PAID]: 209, [CHART_FOR.CANCELED]: 130 },
	{ month: MONTHS.JUNIO, [CHART_FOR.PAID]: 214, [CHART_FOR.CANCELED]: 140 },
]
