/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as RoleRouteRouteImport } from './routes/$role/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as RoleIndexRouteImport } from './routes/$role/index'
import { Route as AuthSetupIndexRouteImport } from './routes/auth/setup/index'
import { Route as AuthRecoverIndexRouteImport } from './routes/auth/recover/index'
import { Route as RoleProfileIndexRouteImport } from './routes/$role/profile/index'
import { Route as RoleInvoicingIndexRouteImport } from './routes/$role/invoicing/index'
import { Route as RoleInventoryIndexRouteImport } from './routes/$role/inventory/index'
import { Route as RoleDebtsIndexRouteImport } from './routes/$role/debts/index'
import { Route as RoleSettingsRolesIndexRouteImport } from './routes/$role/settings/roles/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleRouteRoute = RoleRouteRouteImport.update({
  id: '/$role',
  path: '/$role',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const RoleIndexRoute = RoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoleRouteRoute,
} as any)
const AuthSetupIndexRoute = AuthSetupIndexRouteImport.update({
  id: '/setup/',
  path: '/setup/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRecoverIndexRoute = AuthRecoverIndexRouteImport.update({
  id: '/recover/',
  path: '/recover/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const RoleProfileIndexRoute = RoleProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => RoleRouteRoute,
} as any)
const RoleInvoicingIndexRoute = RoleInvoicingIndexRouteImport.update({
  id: '/invoicing/',
  path: '/invoicing/',
  getParentRoute: () => RoleRouteRoute,
} as any)
const RoleInventoryIndexRoute = RoleInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => RoleRouteRoute,
} as any)
const RoleDebtsIndexRoute = RoleDebtsIndexRouteImport.update({
  id: '/debts/',
  path: '/debts/',
  getParentRoute: () => RoleRouteRoute,
} as any)
const RoleSettingsRolesIndexRoute = RoleSettingsRolesIndexRouteImport.update({
  id: '/settings/roles/',
  path: '/settings/roles/',
  getParentRoute: () => RoleRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$role': typeof RoleRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/$role/': typeof RoleIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/$role/debts': typeof RoleDebtsIndexRoute
  '/$role/inventory': typeof RoleInventoryIndexRoute
  '/$role/invoicing': typeof RoleInvoicingIndexRoute
  '/$role/profile': typeof RoleProfileIndexRoute
  '/auth/recover': typeof AuthRecoverIndexRoute
  '/auth/setup': typeof AuthSetupIndexRoute
  '/$role/settings/roles': typeof RoleSettingsRolesIndexRoute
}
export interface FileRoutesByTo {
  '/$role': typeof RoleIndexRoute
  '/auth': typeof AuthIndexRoute
  '/$role/debts': typeof RoleDebtsIndexRoute
  '/$role/inventory': typeof RoleInventoryIndexRoute
  '/$role/invoicing': typeof RoleInvoicingIndexRoute
  '/$role/profile': typeof RoleProfileIndexRoute
  '/auth/recover': typeof AuthRecoverIndexRoute
  '/auth/setup': typeof AuthSetupIndexRoute
  '/$role/settings/roles': typeof RoleSettingsRolesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$role': typeof RoleRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/$role/': typeof RoleIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/$role/debts/': typeof RoleDebtsIndexRoute
  '/$role/inventory/': typeof RoleInventoryIndexRoute
  '/$role/invoicing/': typeof RoleInvoicingIndexRoute
  '/$role/profile/': typeof RoleProfileIndexRoute
  '/auth/recover/': typeof AuthRecoverIndexRoute
  '/auth/setup/': typeof AuthSetupIndexRoute
  '/$role/settings/roles/': typeof RoleSettingsRolesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$role'
    | '/auth'
    | '/$role/'
    | '/auth/'
    | '/$role/debts'
    | '/$role/inventory'
    | '/$role/invoicing'
    | '/$role/profile'
    | '/auth/recover'
    | '/auth/setup'
    | '/$role/settings/roles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$role'
    | '/auth'
    | '/$role/debts'
    | '/$role/inventory'
    | '/$role/invoicing'
    | '/$role/profile'
    | '/auth/recover'
    | '/auth/setup'
    | '/$role/settings/roles'
  id:
    | '__root__'
    | '/$role'
    | '/auth'
    | '/$role/'
    | '/auth/'
    | '/$role/debts/'
    | '/$role/inventory/'
    | '/$role/invoicing/'
    | '/$role/profile/'
    | '/auth/recover/'
    | '/auth/setup/'
    | '/$role/settings/roles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RoleRouteRoute: typeof RoleRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$role': {
      id: '/$role'
      path: '/$role'
      fullPath: '/$role'
      preLoaderRoute: typeof RoleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/$role/': {
      id: '/$role/'
      path: '/'
      fullPath: '/$role/'
      preLoaderRoute: typeof RoleIndexRouteImport
      parentRoute: typeof RoleRouteRoute
    }
    '/auth/setup/': {
      id: '/auth/setup/'
      path: '/setup'
      fullPath: '/auth/setup'
      preLoaderRoute: typeof AuthSetupIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/recover/': {
      id: '/auth/recover/'
      path: '/recover'
      fullPath: '/auth/recover'
      preLoaderRoute: typeof AuthRecoverIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/$role/profile/': {
      id: '/$role/profile/'
      path: '/profile'
      fullPath: '/$role/profile'
      preLoaderRoute: typeof RoleProfileIndexRouteImport
      parentRoute: typeof RoleRouteRoute
    }
    '/$role/invoicing/': {
      id: '/$role/invoicing/'
      path: '/invoicing'
      fullPath: '/$role/invoicing'
      preLoaderRoute: typeof RoleInvoicingIndexRouteImport
      parentRoute: typeof RoleRouteRoute
    }
    '/$role/inventory/': {
      id: '/$role/inventory/'
      path: '/inventory'
      fullPath: '/$role/inventory'
      preLoaderRoute: typeof RoleInventoryIndexRouteImport
      parentRoute: typeof RoleRouteRoute
    }
    '/$role/debts/': {
      id: '/$role/debts/'
      path: '/debts'
      fullPath: '/$role/debts'
      preLoaderRoute: typeof RoleDebtsIndexRouteImport
      parentRoute: typeof RoleRouteRoute
    }
    '/$role/settings/roles/': {
      id: '/$role/settings/roles/'
      path: '/settings/roles'
      fullPath: '/$role/settings/roles'
      preLoaderRoute: typeof RoleSettingsRolesIndexRouteImport
      parentRoute: typeof RoleRouteRoute
    }
  }
}

interface RoleRouteRouteChildren {
  RoleIndexRoute: typeof RoleIndexRoute
  RoleDebtsIndexRoute: typeof RoleDebtsIndexRoute
  RoleInventoryIndexRoute: typeof RoleInventoryIndexRoute
  RoleInvoicingIndexRoute: typeof RoleInvoicingIndexRoute
  RoleProfileIndexRoute: typeof RoleProfileIndexRoute
  RoleSettingsRolesIndexRoute: typeof RoleSettingsRolesIndexRoute
}

const RoleRouteRouteChildren: RoleRouteRouteChildren = {
  RoleIndexRoute: RoleIndexRoute,
  RoleDebtsIndexRoute: RoleDebtsIndexRoute,
  RoleInventoryIndexRoute: RoleInventoryIndexRoute,
  RoleInvoicingIndexRoute: RoleInvoicingIndexRoute,
  RoleProfileIndexRoute: RoleProfileIndexRoute,
  RoleSettingsRolesIndexRoute: RoleSettingsRolesIndexRoute,
}

const RoleRouteRouteWithChildren = RoleRouteRoute._addFileChildren(
  RoleRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthRecoverIndexRoute: typeof AuthRecoverIndexRoute
  AuthSetupIndexRoute: typeof AuthSetupIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthRecoverIndexRoute: AuthRecoverIndexRoute,
  AuthSetupIndexRoute: AuthSetupIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  RoleRouteRoute: RoleRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
