/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as RoleRouteRouteImport } from './routes/$role/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as RoleIndexRouteImport } from './routes/$role/index'
import { Route as AuthSetupRouteImport } from './routes/auth/setup'
import { Route as AuthRecoverRouteImport } from './routes/auth/recover'
import { Route as RoleSettingsRolesIndexRouteImport } from './routes/$role/settings/roles/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleRouteRoute = RoleRouteRouteImport.update({
  id: '/$role',
  path: '/$role',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const RoleIndexRoute = RoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoleRouteRoute,
} as any)
const AuthSetupRoute = AuthSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRecoverRoute = AuthRecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => AuthRouteRoute,
} as any)
const RoleSettingsRolesIndexRoute = RoleSettingsRolesIndexRouteImport.update({
  id: '/settings/roles/',
  path: '/settings/roles/',
  getParentRoute: () => RoleRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$role': typeof RoleRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/recover': typeof AuthRecoverRoute
  '/auth/setup': typeof AuthSetupRoute
  '/$role/': typeof RoleIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/$role/settings/roles': typeof RoleSettingsRolesIndexRoute
}
export interface FileRoutesByTo {
  '/auth/recover': typeof AuthRecoverRoute
  '/auth/setup': typeof AuthSetupRoute
  '/$role': typeof RoleIndexRoute
  '/auth': typeof AuthIndexRoute
  '/$role/settings/roles': typeof RoleSettingsRolesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$role': typeof RoleRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/recover': typeof AuthRecoverRoute
  '/auth/setup': typeof AuthSetupRoute
  '/$role/': typeof RoleIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/$role/settings/roles/': typeof RoleSettingsRolesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$role'
    | '/auth'
    | '/auth/recover'
    | '/auth/setup'
    | '/$role/'
    | '/auth/'
    | '/$role/settings/roles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/recover'
    | '/auth/setup'
    | '/$role'
    | '/auth'
    | '/$role/settings/roles'
  id:
    | '__root__'
    | '/$role'
    | '/auth'
    | '/auth/recover'
    | '/auth/setup'
    | '/$role/'
    | '/auth/'
    | '/$role/settings/roles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RoleRouteRoute: typeof RoleRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$role': {
      id: '/$role'
      path: '/$role'
      fullPath: '/$role'
      preLoaderRoute: typeof RoleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/$role/': {
      id: '/$role/'
      path: '/'
      fullPath: '/$role/'
      preLoaderRoute: typeof RoleIndexRouteImport
      parentRoute: typeof RoleRouteRoute
    }
    '/auth/setup': {
      id: '/auth/setup'
      path: '/setup'
      fullPath: '/auth/setup'
      preLoaderRoute: typeof AuthSetupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/recover': {
      id: '/auth/recover'
      path: '/recover'
      fullPath: '/auth/recover'
      preLoaderRoute: typeof AuthRecoverRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/$role/settings/roles/': {
      id: '/$role/settings/roles/'
      path: '/settings/roles'
      fullPath: '/$role/settings/roles'
      preLoaderRoute: typeof RoleSettingsRolesIndexRouteImport
      parentRoute: typeof RoleRouteRoute
    }
  }
}

interface RoleRouteRouteChildren {
  RoleIndexRoute: typeof RoleIndexRoute
  RoleSettingsRolesIndexRoute: typeof RoleSettingsRolesIndexRoute
}

const RoleRouteRouteChildren: RoleRouteRouteChildren = {
  RoleIndexRoute: RoleIndexRoute,
  RoleSettingsRolesIndexRoute: RoleSettingsRolesIndexRoute,
}

const RoleRouteRouteWithChildren = RoleRouteRoute._addFileChildren(
  RoleRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthRecoverRoute: typeof AuthRecoverRoute
  AuthSetupRoute: typeof AuthSetupRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthRecoverRoute: AuthRecoverRoute,
  AuthSetupRoute: AuthSetupRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  RoleRouteRoute: RoleRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
